apiVersion: v1
kind: Service
metadata:
  name: eks-example
  namespace: eks-example
  labels:
    app: eks-example

spec:
  type: NodePort
  ports:
    - port: 5678
      targetPort: http
      protocol: TCP
  selector:
    app: eks-example
